import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Recent Complaint': 'Recent Complaint',
      'Departments': 'Departments',
      'complaint_line':
          'To register your complaint online\n select the appropriate section below.',
      'About Us': 'About Us',
      'About Us2': 'About Us',
      'Complaints': 'Complaints',
      'Links': 'Links',
      'Important Links': 'Important Links',
      'Pay Water Bills': 'Pay Water Bills',
      'Pay your Property Dues': 'Pay your Property Dues',
      'Birth Registration Search': 'Birth Registration Search',
      'Death Registration Search': 'Death Registration Search',
      'Public Commitments': 'Public Commitments',
      'Audit Reports': 'Audit Reports',
      'Description of the Complaint': 'Description of the Complaint',
      'Profile': 'Profile',
      'User Details': 'User Details',
      'Name': 'Name',
      'Enter your Mobile Number': 'Enter your Mobile Number',
      'Number': 'Number',
      'Mobile Number': 'Mobile Number *',
      'Enter your Number': 'Enter your Number',
      'My Profile': 'My Profile',
      'Log Out': 'Log Out',
      'Register Complaint': 'Register Complaint',
      'Track Complaint': 'Track Complaint',
      'Be a Responsible Citizen': 'Be a Responsible Citizen',
      'slider1Text':
          'Effortlessly register complaints with our user-friendly interface, ensuring a swift and seamless process for addressing your concerns.',
      'slider2Text':
          'Track the status of your complaints in real-time, empowering you with transparency and visibility into the resolution progress',
      'slider3Text':
          'Promote responsible citizenship by actively participating in the resolution journey, making a positive impact in our community.',
      'Confirm OTP': 'Confirm OTP',
      'A verification code has been sent to':
          'A verification code has been sent to',
      'Resend OTP': 'Resend OTP',
      'Resend OTP in 00': 'Resend OTP',
      'seconds': 'seconds',
      'Send OTP': 'Send OTP',
      'Enter valid phone number': 'Enter valid phone number',
      'No Data Found': 'No Data Found',
      'Search...': 'Search...',
      'apology':
          'We apologize for any inconvenience caused your complaint has been successfully registered, and we will get back to you shortly.',
      'Complaint Summary': 'Complaint Summary',
      'SUMMARY': 'SUMMARY',
      'CODE : ': 'CODE : ',
      'Confirm Account Deletion': 'Confirm Account Deletion',
      'Are you sure you want to delete your account?':
          'Are you sure you want to delete your account?',
      'Cancel': 'Cancel',
      'Yes': 'Yes',
      'Name :': 'Name :',
      'Mobile No :': 'Mobile No :',
      'Date & Time :': 'Date & Time :',
      'Department :': 'Department :',
      'Ward :': 'Ward :',
      'Status :': 'Status :',
      'Description :': 'Description :',
      'Attachments :': 'Attachments :',
      'Notifications': 'Notifications',
      'Complaint Type': 'Complaint Type',
      'Complaint Registration': 'Complaint Registration',
      'ward *': 'Ward *',
      'ward': 'Ward',
      'Complaint Details': 'Complaint Details',
      'Select Ward': 'Select Ward',
      'RTI Details': 'RTI Details',
      'Please select Ward': 'Please select Ward',
      'Nearest Landmark': 'Area / Nearest Landmark',
      'Landmark :': 'Landmark :',
      'Landmark': 'Landmark',
      'Enter your Landmark': 'Enter your Landmark',
      'Enter your Description of the Complaint':
          'Enter your Description of the Complaint',
      'Attach Documents *': 'Attach Documents',
      'Attach Documents': 'Attach Documents',
      'Submit': 'Submit',
      'Sign Up': 'Sign Up',
      'OTP': 'OTP',
      'Logging in': 'Logging in',
      'Processing': 'Processing',
      'Subject *': 'Subject *',
      'Subject': 'Subject',
      'RTI': 'RTI',
      'Home': 'Home',
      'CODE :': 'CODE :',
      'You have reached at end of this page':
          'You have reached at end of this page',
      'Enter your Subject': 'Enter your Subject',
      'RTI Application': 'RTI Application',
      'Add New RTI': 'Add New RTI',
      'locationDialog':
          'The PNP app gathers location information so that users can find nearby locations .',
      'Please Enter your Details to proceed Further':
          'Please Enter your Details to proceed Further',
      'Use your location': 'Use your location',
      'Are you sure ?': 'Are you sure ?',
      'User Manual': 'User Manual',
      'Delete Account': 'Delete Account',
      'Privacy Policy.': 'Privacy Policy.',
      'We are sorry to see you go!': 'We are sorry to see you go!',
      '• You acknowledge that you have read our ':
          '• You acknowledge that you have read our ',
      'DeleteLine':
          'Please note that once you choose to delete your account, your account will no longer be available to you and you will not be able to activate or use the account again.',
      'logoutLine':
          'If you cant accept location permission then you dont use app \nAre you sure you want to logout?',

      //Bullet point delete account
      'All your data will be permanently deleted':
          'All your data will be permanently deleted',
      'This action cannot be undone': 'This action cannot be undone',
      'You will lose access to all account features':
          'You will lose access to all account features',
      'By proceeding, you acknowledge our':
          'By proceeding, you acknowledge our',
      'Delete My Account': 'Delete My Account',
      'Confirm Deletion': 'Confirm Deletion',
      'Are you absolutely sure you want to delete your account? This action cannot be undone.':
          'Are you absolutely sure you want to delete your account? This action cannot be undone.',
      'Before you proceed:': 'Before you proceed:',
    },
    'mr': {
      'Confirm Account Deletion': 'खाते हटवण्याची पुष्टी करा',
      'Are you sure you want to delete your account?':
          'तुम्हाला खातं हटवायचं आहे का?',
      'Cancel': 'रद्द करा',
      'Yes': 'हो',
      'Recent Complaint': 'शेवटची तक्रार',
      'Search...': 'शोधा...',
      'Departments': 'विभाग',
      'complaint_line':
          'ऑनलाईन पध्दतीने तुमची तक्रार नोंद करण्यासाठी\n खालीलपैकी योग्य विभाग निवडा.',
      'About Us': 'आमच्याबद्दल माहिती',
      'About Us2': 'माहिती',
      'Complaints': 'तक्रारी',
      'Links': 'लिंक्स',
      'Important Links': 'महत्वाच्या लिंक्स',
      'Pay Water Bills': 'पाण्याची बिले भरा',
      'Complaint Type': 'तक्रारीचा प्रकार',
      'Pay your Property Dues': 'तुमची मालमत्ता थकबाकी भरा',
      'Birth Registration Search': 'जन्म नोंदणी शोध',
      'Death Registration Search': 'मृत्यू नोंदणी शोध',
      'Public Commitments': 'सार्वजनिक वचनबद्धता',
      'Audit Reports': 'लेखापरीक्षण अहवाल',
      'Profile': 'प्रोफाइल',
      'User Details': 'वापरकर्ता तपशील',
      'Name': 'नाव',
      'Enter your Name': 'आपले नांव लिहा',
      'Number': 'क्रमांक',
      'Mobile Number': 'मोबाईल नंबर *',
      'Enter your Mobile Number': 'तुमचा मोबाईल नंबर टाका',
      'My Profile': 'माझे प्रोफाइल',
      'Log Out': 'लॉगआऊट',
      'Home': 'होम',
      'Logging in': 'लॉग इन करत आहे',
      'Register Complaint': 'तक्रार नोंदवा',
      'Track Complaint': 'तक्रारीचा मागोवा घ्या',
      'Be a Responsible Citizen': 'एक जबाबदार नागरिक व्हा',
      'slider1Text':
          'तुमच्या समस्यांचे निराकरण करण्यासाठी जलद आणि अखंड प्रक्रिया सुनिश्चित करून आमच्या वापरकर्ता-अनुकूल इंटरफेसवर सहजतेने तक्रारी नोंदवा.',
      'slider2Text':
          'रिअल-टाइममध्ये तुमच्या तक्रारींच्या स्थितीचा मागोवा घ्या, तुम्हाला पारदर्शकता आणि दृश्यमानता देऊन समाधानाच्या प्रगतीमध्ये',
      'slider3Text':
          'रिझोल्यूशनच्या प्रवासात सक्रिय सहभाग घेऊन जबाबदार नागरिकत्वाचा प्रचार करा, आमच्या समुदायावर सकारात्मक प्रभाव पाडा.',
      'Confirm OTP': 'OTP ची पुष्टी करा',
      'A verification code has been sent to': 'वर पडताळणी कोड पाठवला आहे',
      'Resend OTP': 'OTP पुन्हा पाठवा',
      'Resend OTP in 00': ' OTP पुन्हा पाठवा 00 ',
      'seconds': 'सेकंद',
      'Enter your Subject': 'तुमचा विषय प्रविष्ट करा',
      'RTI Details': 'आरटीआय तपशील',
      'Send OTP': 'OTP पाठवा',
      'Enter valid phone number': 'वैध फोन नंबर प्रविष्ट करा',
      'No Data Found': 'माहिती आढळली नाही',
      'apology':
          'आपणास झालेल्या गैरसोयीबद्दल आम्ही दिलगीर आहोत. \nतुमची तक्रार यशस्वीरित्या नोंदवण्यात आली आहे आणि \n आम्ही लवकरच तुमच्याशी संपर्क साधू.',
      'Complaint Summary': 'तक्रारीचा सारांश',
      'SUMMARY': 'सारांश',
      'CODE : ': 'कोड : ',
      'Name :': 'नाव :',
      'CODE :': 'कोड :',
      'Mobile No :': 'मोबाईल क्र :',
      'Processing': 'प्रक्रिया करत आहे',
      'Date & Time :': 'तारीख वेळ :',
      'Department :': 'विभाग :',
      'Ward :': 'वार्ड :',
      'Delete Account': 'अकाउंट डिलीट',
      'Status :': 'स्थिती :',
      'Description :': 'वर्णन :',
      'Attachments :': 'अटॅचमेंट :',
      'Notifications': 'सूचना',
      'Complaint Registration': 'तक्रार नोंदणी',
      'ward *': 'वार्ड *',
      'ward': 'वार्ड',
      'You have reached at end of this page':
          'तुम्ही या पानाच्या शेवटी पोहोचला आहात',
      'Complaint Details': 'तक्रारीचे तपशील',
      'Select Ward': 'प्रभाग निवडा',
      'Please select Ward': 'कृपया प्रभाग निवडा',
      'Nearest Landmark': 'स्थळ / आसपासचा ठिकाण',
      'Landmark :': 'जवळची खूण :',
      'Landmark': 'जवळची खूण',
      'Subject *': 'विषय*',
      'Subject': 'विषय',
      'User Manual': 'युजर मॅन्युअल',
      'Enter your Landmark': 'तुमची जवळची खूण एंटर करा',
      'Description of the Complaint': 'तक्रारीचे वर्णन',
      'Enter your Description of the Complaint':
          'तुमच्या तक्रारीचे वर्णन प्रविष्ट करा',
      'Attach Documents *': 'कागदपत्र अपलोड करा *',
      'Attach Documents': 'कागदपत्र अपलोड करा',
      'Submit': 'सबमिट',
      'Sign Up': 'साइन अप करा',
      'OTP': 'OTP',
      'RTI': 'आरटीआय',
      'RTI Application': 'आरटीआय अर्ज',
      'Add New RTI': 'नवीन आरटीआय जोडा',
      'Use your location': 'तुमचे लोकेशन वापरा',
      'locationDialog':
          'PNP ॲप स्थान माहिती गोळा करते जेणेकरून वापरकर्ते जवळपासची ठिकाणे शोधू शकतील.',
      'Please Enter your Details to proceed Further':
          'पुढे जाण्यासाठी कृपया तुमचे तपशील प्रविष्ट करा',
      'Are you sure ?': 'तुला खात्री आहे ?',
      'Privacy Policy.': 'गोपनीयता धोरण.',
      'We are sorry to see you go!':
          'तुम्हाला जाताना पाहून आम्हाला वाईट वाटते!',
      '• You acknowledge that you have read our ':
          '• तुम्ही कबूल करता की तुम्ही आमचे वाचले आहे ',
      'DeleteLine':
          'कृपया लक्षात घ्या की एकदा तुम्ही तुमचे खाते हटवणे निवडले की, तुमचे खाते यापुढे तुमच्यासाठी उपलब्ध राहणार नाही आणि तुम्ही ते खाते पुन्हा सक्रिय करू शकणार नाही किंवा वापरू शकणार नाही.',

      'All your data will be permanently deleted':
          'तुमचा सर्व डेटा कायमस्वरूपी हटवला जाईल.',
      'This action cannot be undone': 'ही कृती पूर्ववत करता येणार नाही.',
      'You will lose access to all account features':
          'तुम्ही खात्याच्या सर्व वैशिष्ट्यांचा वापर गमावून बसाल.',
      'By proceeding, you acknowledge our':
          'पुढे जाऊन, तुम्ही आमच्या अटी व शर्ती मान्य करता ',
      'Delete My Account': 'माझे खाते हटवा',
      'Before you proceed:': 'आपण पुढे जाण्यापूर्वी:',
      'Confirm Deletion': 'हटवण्याची पुष्टी करा',
      'Are you absolutely sure you want to delete your account? This action cannot be undone.':
          'तुम्हाला तुमचे खाते हटवायचे आहे याची तुम्हाला पूर्ण खात्री आहे का? ही कृती पूर्ववत करता येणार नाही.',
    },
  };
}
